# Generated by Django 6.0.1 on 2026-02-04 06:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='dailylog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='user_serving_grams',
            field=models.FloatField(default=100.0, help_text='Amount consumed in grams (e.g., 150.0)'),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
