from django.contrib.auth import get_user_model
from django.db import transaction
from django.utils import timezone
from drf_yasg import openapi
from drf_yasg.utils import swagger_auto_schema
from rest_framework import permissions, status, views, viewsets
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.response import Response

from apps.foods.models import FoodImage, FoodItem

from .models import DailyLog, ExerciseLog
from .serializers import DailyLogSerializer, ExerciseLogSerializer

User = get_user_model()


class DailyLogViewSet(viewsets.ModelViewSet):
    serializer_class = DailyLogSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return DailyLog.objects.filter(user=self.request.user)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    @swagger_auto_schema(
        operation_description="Log a new food item for the authenticated user.",
        tags=["Daily Logs"],
        responses={
            201: "Food logged successfully",
            400: "Bad Request",
        },
    )
    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        return Response(
            {"message": "Food logged successfully", "success": True},
            status=status.HTTP_201_CREATED,
        )

    @swagger_auto_schema(
        operation_description="Retrieve a summarized list of daily food logs grouped by meal type.",
        tags=["Daily Logs"],
        manual_parameters=[
            openapi.Parameter(
                "date",
                openapi.IN_QUERY,
                description="Date in YYYY-MM-DD format (defaults to today)",
                type=openapi.TYPE_STRING,
            )
        ],
        responses={200: "Daily logs grouped by meal"},
    )
    def list(self, request, *args, **kwargs):
        date_str = request.query_params.get("date", str(timezone.now().date()))

        logs = DailyLog.objects.filter(user=request.user, date=date_str).select_related(
            "food_item"
        )

        response_data = {
            "user_id": request.user.id,
            "date": date_str,
            "total_grant_calories": 0,
            "meals": [],
        }

        meal_groups = {
            "BREAKFAST": {
                "meal_type": "breakfast",
                "total_meal_calories": 0,
                "items": [],
            },
            "LUNCH": {"meal_type": "lunch", "total_meal_calories": 0, "items": []},
            "DINNER": {"meal_type": "dinner", "total_meal_calories": 0, "items": []},
            "SNACK": {"meal_type": "snack", "total_meal_calories": 0, "items": []},
        }

        for log in logs:
            serialized_item = DailyLogSerializer(log).data
            if serialized_item.get("food_details"):
                item_calories = serialized_item["food_details"]["calories"]

                meal_key = log.meal_type
                if meal_key in meal_groups:
                    meal_groups[meal_key]["items"].append(serialized_item)
                    meal_groups[meal_key]["total_meal_calories"] += item_calories
                    response_data["total_grant_calories"] += item_calories

        response_data["meals"] = list(meal_groups.values())

        return Response(response_data)


class LogAIMealView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Logs multiple food items generated by AI to a specific meal type.",
        tags=["AI Meals"],
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "meal_type": openapi.Schema(
                    type=openapi.TYPE_STRING, description="e.g., SNACK, BREAKFAST"
                ),
                "date": openapi.Schema(
                    type=openapi.TYPE_STRING, description="YYYY-MM-DD"
                ),
                "items": openapi.Schema(
                    type=openapi.TYPE_ARRAY,
                    items=openapi.Schema(
                        type=openapi.TYPE_OBJECT,
                        description="AI generated food item data",
                    ),
                ),
            },
            required=["items"],
        ),
        responses={
            201: "AI Meal logged successfully",
            400: "No items provided",
            500: "Internal Server Error",
        },
    )
    def post(self, request):

        data = request.data
        user = request.user

        meal_type = data.get("meal_type", "SNACK").upper()
        date_str = data.get("date", str(timezone.now().date()))

        ai_items = data.get("items", [])

        if not ai_items:
            return Response(
                {"error": "No items provided in the AI response"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            with transaction.atomic():
                created_logs = []

                for item in ai_items:
                    food_name = item.get("food_name")
                    details_100g = item.get("100g_serving_size", {})

                    food_defaults = {
                        "name": food_name,
                        "serving_size": "100g",
                        "calories": details_100g.get("calories", 0),
                        "protein": details_100g.get("protein", 0),
                        "carbohydrates": details_100g.get("carbs", 0),
                        "fat": details_100g.get("fats", 0),
                        "fiber": details_100g.get("fiber", 0),
                        "sugar": details_100g.get("sugar", 0),
                        "saturated_fat": details_100g.get("saturated_fat", 0),
                        "sodium": details_100g.get("sodium", 0),
                        "cholesterol": details_100g.get("cholesterol", 0),
                        "source": "AI",
                        "is_public": True,
                        "is_verified": False,
                        "votes": 0,
                    }

                    food_item, _ = FoodItem.objects.get_or_create(
                        name__iexact=food_name, defaults=food_defaults
                    )

                    user_grams = item.get("user_serving_size_g", 100)

                    log = DailyLog.objects.create(
                        user=user,
                        food_item=food_item,
                        user_serving_grams=user_grams,
                        meal_type=meal_type,
                        date=date_str,
                    )
                    created_logs.append(log.id)

            return Response(
                {
                    "message": "AI Meal logged successfully",
                    "logs_created": len(created_logs),
                    "success": True,
                },
                status=status.HTTP_201_CREATED,
            )

        except Exception as e:
            return Response(
                {"error": str(e), "success": False},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class LogManualFoodView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]
    parser_classes = (MultiPartParser, FormParser)

    @swagger_auto_schema(
        operation_description="Upload a custom food item with multiple images and log it for the user.",
        tags=["Manual Food"],
        consumes=["multipart/form-data"],
        manual_parameters=[
            openapi.Parameter(
                "name", openapi.IN_FORM, type=openapi.TYPE_STRING, required=True
            ),
            openapi.Parameter(
                "user_serving_grams",
                openapi.IN_FORM,
                type=openapi.TYPE_NUMBER,
                required=True,
            ),
            openapi.Parameter("meal_type", openapi.IN_FORM, type=openapi.TYPE_STRING),
            openapi.Parameter("date", openapi.IN_FORM, type=openapi.TYPE_STRING),
            openapi.Parameter("calories", openapi.IN_FORM, type=openapi.TYPE_NUMBER),
            openapi.Parameter(
                "images",
                openapi.IN_FORM,
                type=openapi.TYPE_ARRAY,
                items=openapi.Schema(type=openapi.TYPE_FILE),
            ),
        ],
        responses={
            201: "Food logged with multiple images successfully",
            400: "Invalid data or missing requirements",
            500: "Internal Server Error",
        },
    )
    def post(self, request):
        data = request.data
        user = request.user

        meal_type = data.get("meal_type", "SNACK").upper()
        date_str = data.get("date", str(timezone.now().date()))

        try:
            user_serving_grams = float(data.get("user_serving_grams", 100))
            if user_serving_grams <= 0:
                raise ValueError
        except ValueError:
            return Response({"error": "Invalid serving weight"}, status=400)

        normalization_factor = 100 / user_serving_grams

        def get_normalized_value(key):
            val = data.get(key)
            if val in [None, "", "null", "undefined"]:
                return 0.0
            try:
                user_value = float(val)
                return round(user_value * normalization_factor, 2)
            except ValueError:
                return 0.0

        food_name = data.get("name")
        if not food_name:
            return Response({"error": "Food name is required"}, status=400)

        try:
            with transaction.atomic():
                food_item = FoodItem.objects.create(
                    name=food_name,
                    brand=data.get("brand", ""),
                    serving_size="100g",
                    calories=int(get_normalized_value("calories")),
                    protein=get_normalized_value("protein"),
                    carbohydrates=get_normalized_value("carbohydrates"),
                    fat=get_normalized_value("fat"),
                    fiber=get_normalized_value("fiber"),
                    sugar=get_normalized_value("sugar"),
                    saturated_fat=get_normalized_value("saturated_fat"),
                    sodium=get_normalized_value("sodium"),
                    cholesterol=get_normalized_value("cholesterol"),
                    source="USER",
                    is_public=True,
                    is_verified=False,
                    created_by=user,
                    votes=0,
                )

                images = request.FILES.getlist("images")

                for img in images:
                    FoodImage.objects.create(food=food_item, image=img)

                log = DailyLog.objects.create(
                    user=user,
                    food_item=food_item,
                    user_serving_grams=user_serving_grams,
                    meal_type=meal_type,
                    date=date_str,
                )

                return Response(
                    {
                        "message": "Food logged with multiple images successfully",
                        "log_id": log.id,
                        "food_id": food_item.id,
                        "images_uploaded": len(images),
                        "success": True,
                    },
                    status=status.HTTP_201_CREATED,
                )

        except Exception as e:
            return Response(
                {"error": str(e), "success": False},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )


class LogExerciseView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Log an exercise session for the authenticated user.",
        tags=["Exercise Logs"],
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "exercise": openapi.Schema(
                    type=openapi.TYPE_INTEGER, description="ID of the Exercise"
                ),
                "duration_minutes": openapi.Schema(
                    type=openapi.TYPE_INTEGER,
                    description="Duration in minutes (e.g., 30)",
                ),
                "date": openapi.Schema(
                    type=openapi.TYPE_STRING, description="Date in YYYY-MM-DD format"
                ),
            },
            required=["exercise", "duration_minutes"],
        ),
        responses={
            201: openapi.Response("Exercise logged successfully"),
            400: "Invalid data provided",
        },
    )
    def post(self, request):
        if "date" not in request.data:
            request.data["date"] = str(timezone.now().date())

        serializer = ExerciseLogSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save(user=request.user)
            return Response(
                {
                    "message": "Exercise logged successfully",
                    "success": True,
                    "data": serializer.data,
                },
                status=status.HTTP_201_CREATED,
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ExerciseLogListView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Retrieve a list of logged exercises and total burned calories for a specific date.",
        tags=["Exercise Logs"],
        manual_parameters=[
            openapi.Parameter(
                "date",
                openapi.IN_QUERY,
                description="Date in YYYY-MM-DD format (defaults to today)",
                type=openapi.TYPE_STRING,
            )
        ],
        responses={
            200: openapi.Response(
                description="Exercise logs and burned calories",
                schema=openapi.Schema(
                    type=openapi.TYPE_OBJECT,
                    properties={
                        "user_id": openapi.Schema(type=openapi.TYPE_INTEGER),
                        "date": openapi.Schema(type=openapi.TYPE_STRING),
                        "total_burned_calories": openapi.Schema(
                            type=openapi.TYPE_INTEGER
                        ),
                        "exercises": openapi.Schema(
                            type=openapi.TYPE_ARRAY,
                            items=openapi.Schema(type=openapi.TYPE_OBJECT),
                        ),
                    },
                ),
            )
        },
    )
    def get(self, request):
        date_str = request.query_params.get("date", str(timezone.now().date()))

        exercise_logs = ExerciseLog.objects.filter(
            user=request.user, date=date_str
        ).select_related("exercise", "user__profile")

        response_data = {
            "user_id": request.user.id,
            "date": date_str,
            "total_burned_calories": 0,
            "exercises": [],
        }

        for ex_log in exercise_logs:
            serialized_ex = ExerciseLogSerializer(ex_log).data
            ex_details = serialized_ex.get("exercise_details")
            if ex_details:
                response_data["exercises"].append(ex_details)
                response_data["total_burned_calories"] += ex_details["burned_calories"]

        return Response(response_data, status=status.HTTP_200_OK)


class ExerciseLogDetailView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Update an exercise log (e.g. change duration).",
        tags=["Exercise Logs"],
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            properties={
                "duration_minutes": openapi.Schema(type=openapi.TYPE_INTEGER),
                "date": openapi.Schema(type=openapi.TYPE_STRING, format="date"),
            },
        ),
        responses={200: "Updated successfully", 404: "Not found"},
    )
    def patch(self, request, pk):
        try:

            log = ExerciseLog.objects.get(pk=pk, user=request.user)
        except ExerciseLog.DoesNotExist:
            return Response(
                {"error": "Exercise log not found"}, status=status.HTTP_404_NOT_FOUND
            )

        serializer = ExerciseLogSerializer(log, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(
                {
                    "message": "Exercise log updated successfully",
                    "data": serializer.data,
                },
                status=status.HTTP_200_OK,
            )
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @swagger_auto_schema(
        operation_description="Delete an exercise log.",
        tags=["Exercise Logs"],
        responses={204: "Deleted successfully", 404: "Not found"},
    )
    def delete(self, request, pk):
        try:

            log = ExerciseLog.objects.get(pk=pk, user=request.user)
        except ExerciseLog.DoesNotExist:
            return Response(
                {"error": "Exercise log not found"}, status=status.HTTP_404_NOT_FOUND
            )

        log.delete()
        return Response(
            {"message": "Exercise log deleted successfully", "success": True},
            status=status.HTTP_204_NO_CONTENT,
        )


class PatientDailyLogView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Retrieve a summarized list of daily food logs for a specific patient.",
        tags=["Doctor Tools"],
        manual_parameters=[
            openapi.Parameter(
                "date",
                openapi.IN_QUERY,
                description="Date in YYYY-MM-DD format (defaults to today)",
                type=openapi.TYPE_STRING,
            )
        ],
        responses={200: "Daily logs grouped by meal"},
    )
    def get(self, request, user_id, *args, **kwargs):
        date_str = request.query_params.get("date", str(timezone.now().date()))

        logs = DailyLog.objects.filter(user_id=user_id, date=date_str).select_related(
            "food_item"
        )

        response_data = {
            "user_id": user_id,
            "date": date_str,
            "total_grant_calories": 0,
            "meals": [],
        }

        meal_groups = {
            "BREAKFAST": {
                "meal_type": "breakfast",
                "total_meal_calories": 0,
                "items": [],
            },
            "LUNCH": {"meal_type": "lunch", "total_meal_calories": 0, "items": []},
            "DINNER": {"meal_type": "dinner", "total_meal_calories": 0, "items": []},
            "SNACK": {"meal_type": "snack", "total_meal_calories": 0, "items": []},
        }

        for log in logs:
            serialized_item = DailyLogSerializer(log).data
            if serialized_item.get("food_details"):
                item_calories = serialized_item["food_details"]["calories"]

                meal_key = log.meal_type
                if meal_key in meal_groups:
                    meal_groups[meal_key]["items"].append(serialized_item)
                    meal_groups[meal_key]["total_meal_calories"] += item_calories
                    response_data["total_grant_calories"] += item_calories

        response_data["meals"] = list(meal_groups.values())

        return Response(response_data)


class PatientExerciseLogView(views.APIView):
    permission_classes = [permissions.IsAuthenticated]

    @swagger_auto_schema(
        operation_description="Retrieve a list of logged exercises for a specific patient.",
        tags=["Doctor Tools"],
        manual_parameters=[
            openapi.Parameter(
                "date",
                openapi.IN_QUERY,
                description="Date in YYYY-MM-DD format (defaults to today)",
                type=openapi.TYPE_STRING,
            )
        ],
        responses={200: "Exercise logs and burned calories"},
    )
    def get(self, request, user_id):
        date_str = request.query_params.get("date", str(timezone.now().date()))

        exercise_logs = ExerciseLog.objects.filter(
            user_id=user_id, date=date_str
        ).select_related("exercise", "user__profile")

        response_data = {
            "user_id": user_id,
            "date": date_str,
            "total_burned_calories": 0,
            "exercises": [],
        }

        for ex_log in exercise_logs:
            serialized_ex = ExerciseLogSerializer(ex_log).data
            ex_details = serialized_ex.get("exercise_details")
            if ex_details:
                response_data["exercises"].append(ex_details)
                response_data["total_burned_calories"] += ex_details["burned_calories"]

        return Response(response_data, status=status.HTTP_200_OK)
