# Generated by Django 6.0.1 on 2026-02-18 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("height", models.FloatField(help_text="Height in CM", null=True)),
                (
                    "weight",
                    models.FloatField(help_text="Current Weight in KG", null=True),
                ),
                (
                    "target_weight",
                    models.FloatField(
                        blank=True, help_text="Target Weight in KG", null=True
                    ),
                ),
                (
                    "medical_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of conditions e.g. ['Diabetes', 'PCOS']",
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "Mostly Sitting (Sedentary)"),
                            (1.375, "Lightly Active"),
                            (1.55, "Moderately Active"),
                            (1.725, "Very Active"),
                            (1.9, "Extremely Active"),
                        ],
                        default=1.2,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("LOSE", "Weight Loss"),
                            ("MAINTAIN", "Maintenance"),
                            ("GAIN", "Muscle Gain"),
                        ],
                        default="MAINTAIN",
                        max_length=10,
                    ),
                ),
                ("daily_calorie_goal", models.IntegerField(default=0)),
                ("protein_goal", models.IntegerField(default=0)),
                ("carbs_goal", models.IntegerField(default=0)),
                ("fats_goal", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
