# Generated by Django 6.0.1 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_name_profile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
