# Generated by Django 6.0.1 on 2026-03-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_doctorprofile_employeeprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeprofile",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="qualification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="education",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
