# Generated by Django 6.0.1 on 2026-02-02 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('serving_size', models.CharField(help_text='e.g., 1 cup, 100g', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('calories', models.PositiveIntegerField(help_text='Energy in kcal')),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=2, help_text='Carbs in grams', max_digits=6)),
                ('fat', models.DecimalField(decimal_places=2, help_text='Fat in grams', max_digits=6)),
                ('fiber', models.DecimalField(decimal_places=2, default=0.0, help_text='Fiber in grams', max_digits=6)),
                ('sugar', models.DecimalField(decimal_places=2, default=0.0, help_text='Sugar in grams', max_digits=6)),
                ('saturated_fat', models.DecimalField(decimal_places=2, default=0.0, help_text='Saturated fat in grams', max_digits=6)),
                ('sodium', models.DecimalField(decimal_places=2, default=0.0, help_text='Sodium in mg', max_digits=8)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0.0, help_text='Cholesterol in mg', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
