# Generated by Django 6.0.1 on 2026-02-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='source',
            field=models.CharField(choices=[('AI', 'AI Generated'), ('USER', 'User Created'), ('ADMIN', 'Admin Verified'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
