# Generated by Django 6.0.1 on 2026-02-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_fooditem_source_fooditem_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="food_images/"),
        ),
    ]
