# Generated by Django 6.0.1 on 2026-02-10 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0003_fooditem_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="image",
        ),
        migrations.CreateModel(
            name="FoodImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="food_images/")),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="foods.fooditem",
                    ),
                ),
            ],
        ),
    ]
